### PR TITLE
feat: [PAGOPA-883] allowed private bundle type

### PR DESCRIPTION
**Pull request by alessio-acitelli**
#### List of Changes

- allowed private bundle type in createBundleRequest

#### Motivation and Context

- new business rule

#### How Has This Been Tested?

- junit test

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Review by pasqualespica — APPROVED** [review]

**Pull request merged**
