### PR TITLE
[PAGOPA-1050] remove unique name check: removed check on the name

### PR DESCRIPTION
**Pull request by alessio-acitelli**
#### List of Changes

- removed the check on the name for the bundle (creation and update)

#### Motivation and Context

- it was requested to be able to create bundles with the same name

#### How Has This Been Tested?

- Manual and junit test

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Review by jacopocarlini — APPROVED** [review]
🏆 Excellent

**Pull request merged**
